### ISSUE TITLE
Compiling Skript code into native applications

### ISSUE THREAD

**Issue by AngelGamer29JA** [Crafter-Y/SkriptLang-Compiler#1]
i think this language has a powerful potential so... i was thinking in  write a compiler but for console apps like javascript, python you know.
If you think about it, you could use this language to create a simple console application, or use native libraries and create windows or more.
 
for example.
```bash
window = null
create window in {window}
set window title "Hello, world!"

on {window}:
    if %event-type% is "quit":
        destroy window in {window}
```

**Comment by Crafter-Y** [comment]
This is such a cool idea!
But it is not, what I have this project indended for.  The goal of this project is, to "compile" (translate) Skript Code into a Minecraft Java plugin. The Skript Language itself is only designed for that purpose. But its semantics definetely allow to use it for e.g. Console Applications. 
This project will never compile any code into a Console Application, but only in jar plugins. But if you like to, you could fork this and do it on your own! I would really like to see that happen.
I will continiue developing this project next year, and I would love to hear more feedback about this.
